// Content for the 'New Realeases' section on the front page

export const releases = [
  {
    image: "dansktop.png",
    title: "Dansktop",
    artist: "Ukendt Kunster",
    year: "2023",
    genre: "hip-hop",
    id: "37",
  },
  {
    image: "folkeklubben.png",
    title: "Mere end en klub",
    artist: "Folkeklubben",
    year: "2023",
    genre: "Pop",
    id: "38",
  },
  {
    image: "daftpunk.png",
    title: "Random Access Memories",
    artist: "Daft Punk",
    year: "2023",
    genre: "Elektronisk",
    id: "40",
  },
  {
    image: "thomas-bangalter.png",
    title: "Mythologies",
    artist: "Thomas Bangalter",
    year: "2023",
    genre: "Klassisk",
    id: "39",
  },
  {
    image: "fred-again.png",
    title: "secret life",
    artist: "fred again..",
    year: "2023",
    genre: "elektronisk",
    id: "5",
  },
];

// NEW OBJECT HERE - Content for the 'Articles' section on front page

export const articles = [
  {
    image: "ukendt.jpg",
    type: "NYHED",
    artitle: "Ud af ingenting: Ukendt Kunstner er tilbage med nyt album",
  },
  {
    image: "plade-guide.png",
    type: "GUIDE",
    artitle: "Sådan holder du dine gamle plader flotte i mange år",
  },
  {
    image: "soeren-huss.png",
    type: "PORTRÆT",
    artitle: "Søren Huss: Fra Saybia til gammel mand med hjertesorg",
  },
  {
    image: "donny-benet.png",
    type: "NYHED",
    artitle: 'Donny Benét: "<i>Dette bliver mit yndlingsafkom.</i>"',
  },
  {
    image: "slash.png",
    type: "PORTRÆT",
    artitle: "Husker du Slash? Manden der altid forstod af svinge en spade",
  },
];

// Content for the 'Inspiration' section of the front page

// Covers for the first row

export const covers1 = [
  {
    image: "../img/album-1.png",
    id: "6",
  },
  {
    image: "../img/album-2.png",
    id: "0",
  },
  {
    image: "../img/album-3.png",
    id: "7",
  },
  {
    image: "../img/album-4.png",
    id: "8",
  },
  {
    image: "../img/album-5.png",
    id: "9",
  },
  {
    image: "../img/album-6.png",
    id: "10",
  },
  {
    image: "../img/album-7.png",
    id: "11",
  },
  {
    image: "../img/album-8.png",
    id: "12",
  },
  {
    image: "../img/album-9.png",
    id: "13",
  },
  {
    image: "../img/album-10.png",
    id: "14",
  },
  {
    image: "../img/album-11.png",
    id: "15",
  },
  {
    image: "../img/album-12.png",
    id: "2",
  },
];

export const covers2 = [
  {
    image: "../img/album-1.png",
    id: "6",
  },
  {
    image: "../img/album-2.png",
    id: "0",
  },
  {
    image: "../img/album-3.png",
    id: "7",
  },
  {
    image: "../img/album-4.png",
    id: "8",
  },
  {
    image: "../img/album-5.png",
    id: "9",
  },
  {
    image: "../img/album-6.png",
    id: "10",
  },
  {
    image: "../img/album-7.png",
    id: "11",
  },
  {
    image: "../img/album-8.png",
    id: "12",
  },
  {
    image: "../img/album-9.png",
    id: "13",
  },
  {
    image: "../img/album-10.png",
    id: "14",
  },
  {
    image: "../img/album-11.png",
    id: "15",
  },
  {
    image: "../img/album-12.png",
    id: "2",
  },
];

// Covers for the second row

export const covers3 = [
  {
    image: "../img/album-13.png",
    id: "16",
  },
  {
    image: "../img/album-14.png",
    id: "17",
  },
  {
    image: "../img/album-15.png",
    id: "18",
  },
  {
    image: "../img/album-16.png",
    id: "19",
  },
  {
    image: "../img/album-17.png",
    id: "20",
  },
  {
    image: "../img/album-18.png",
    id: "21",
  },
  {
    image: "../img/album-19.png",
    id: "3",
  },
  {
    image: "../img/album-20.png",
    id: "22",
  },
  {
    image: "../img/album-21.png",
    id: "23",
  },
  {
    image: "../img/album-22.png",
    id: "24",
  },
  {
    image: "../img/album-23.png",
    id: "25",
  },
  {
    image: "../img/album-24.png",
    id: "1",
  },
];

export const covers4 = [
  {
    image: "../img/album-13.png",
    id: "16",
  },
  {
    image: "../img/album-14.png",
    id: "17",
  },
  {
    image: "../img/album-15.png",
    id: "18",
  },
  {
    image: "../img/album-16.png",
    id: "19",
  },
  {
    image: "../img/album-17.png",
    id: "20",
  },
  {
    image: "../img/album-18.png",
    id: "21",
  },
  {
    image: "../img/album-19.png",
    id: "3",
  },
  {
    image: "../img/album-20.png",
    id: "22",
  },
  {
    image: "../img/album-21.png",
    id: "23",
  },
  {
    image: "../img/album-22.png",
    id: "24",
  },
  {
    image: "../img/album-23.png",
    id: "25",
  },
  {
    image: "../img/album-24.png",
    id: "1",
  },
];

// Covers for the third row

export const covers5 = [
  {
    image: "../img/album-25.png",
    id: "26",
  },
  {
    image: "../img/album-26.png",
    id: "27",
  },
  {
    image: "../img/album-27.png",
    id: "28",
  },
  {
    image: "../img/album-28.png",
    id: "29",
  },
  {
    image: "../img/album-29.png",
    id: "30",
  },
  {
    image: "../img/album-30.png",
    id: "31",
  },
  {
    image: "../img/album-31.png",
    id: "32",
  },
  {
    image: "../img/album-32.png",
    id: "33",
  },
  {
    image: "../img/album-33.png",
    id: "34",
  },
  {
    image: "../img/album-34.png",
    id: "4",
  },
  {
    image: "../img/album-35.png",
    id: "35",
  },
  {
    image: "../img/album-36.jpg",
    id: "36",
  },
];

export const covers6 = [
  {
    image: "../img/album-25.png",
    id: "26",
  },
  {
    image: "../img/album-26.png",
    id: "27",
  },
  {
    image: "../img/album-27.png",
    id: "28",
  },
  {
    image: "../img/album-28.png",
    id: "29",
  },
  {
    image: "../img/album-29.png",
    id: "30",
  },
  {
    image: "../img/album-30.png",
    id: "31",
  },
  {
    image: "../img/album-31.png",
    id: "32",
  },
  {
    image: "../img/album-32.png",
    id: "33",
  },
  {
    image: "../img/album-33.png",
    id: "34",
  },
  {
    image: "../img/album-34.png",
    id: "4",
  },
  {
    image: "../img/album-35.png",
    id: "35",
  },
  {
    image: "../img/album-36.jpg",
    id: "36",
  },
];

// Content for the 'Testimonials' section

export const testimonials = [
  {
    image: "../img/anders.png",
    stars: "star-5",
    name: "Anders Jacobsen",
    text: "Fed lokal pladebiks som emmer af historie. Altid højt niveau, du kan nemt få hjælp til finde den vinyl du står og mangler i din samling",
    class: "start-quote",
  },
  {
    image: "../img/karsten.png",
    stars: "star-5",
    name: "Karsten Andersen",
    text: "En super fantastisk pladebutik med et skønt miljø og stemning - er lige blevet 50 år og still going strong",
    class: "",
  },
  {
    image: "../img/susanne.png",
    stars: "star-4",
    name: "Susanne Jensen",
    text: "Altid rigtig god og venlig service, man kan især nyde godt af det store kendskab og passion til musik, de besidder derinde.",
    class: "end-quote",
  },
];

export const medias = [
  {
    title: "VINYL",
    data: "data-media-vinyl",
  },
  {
    title: "CD",
    data: "data-media-cd",
  },
  {
    title: "KASSETTEBÅND",
    data: "data-media-cassette",
  },
];

export const genres = [
  {
    title: "POP",
    data: "data-genre-pop",
  },
  {
    title: "ROCK",
    data: "data-genre-rock",
  },
  {
    title: "DANCE",
    data: "data-genre-dance",
  },
  {
    title: "R&B",
    data: "data-genre-rb",
  },
  {
    title: "ELEKTRONISK",
    data: "data-genre-electronic",
  },
  {
    title: "HIP-HOP",
    data: "data-genre-hiphop",
  },
  {
    title: "HOUSE",
    data: "data-genre-house",
  },
  {
    title: "PUNK",
    data: "data-genre-punk",
  },
  {
    title: "SOUL",
    data: "data-genre-soul",
  },
  {
    title: "KLASSISK",
    data: "data-genre-classic",
  },
  {
    title: "HEAVY METAL",
    data: "data-genre-heavymetal",
  },
  {
    title: "JAZZ",
    data: "data-genre-jazz",
  },
  {
    title: "DISCO",
    data: "data-genre-disco",
  },
  {
    title: "FUNK",
    data: "data-genre-funk",
  },
];

export const inventories = [
  {
    image: "../img/album-2.png",
    vinylImage: "../img/heroes/vinyl.png",
    cdImage: "../img/heroes/cd.png",
    cassetteImage: "../img/heroes/cassette.png",
    albumTitle: "HEROES",
    artist: "DAVID BOWIE",
    year: "1977",
    genre: "rock",
    vinylStock: [1, true],
    cdStock: [3, true],
    cassetteStock: [2, true],
    keywords: "David Bowie Heroes",
    id: "0",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Heroes" er et ikonisk album udgivet af David Bowie i 1977. Det præsenterer en blanding af kunstrock og elektroniske elementer og indeholder tidløse sange som titelnummeret "Heroes", der udstråler Bowies unikke musikalske vision og legendariske status.',
    path: "heroes",
    scrollSpeed: "scroll-speed-medium",
  },
  {
    image: "../img/album-24.png",
    vinylImage: "../img/the-doors/vinyl.png",
    cdImage: "../img/the-doors/cd.png",
    cassetteImage: "../img/the-doors/cassette.png",
    albumTitle: "the doors",
    artist: "the doors",
    year: "1967",
    genre: "rock",
    vinylStock: [5, true],
    cdStock: [3, true],
    cassetteStock: [0, false],
    keywords: "The Doors",
    id: "1",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"The Doors" er det selvbetitlede debutalbum af The Doors fra 1967. Det introducerer Jim Morrisons intense vokal, Ray Manzareks keyboardmagi og bandets psykedeliske rockstil, der eksperimenterer med mørke og mystiske lyde.',
    path: "the-doors",
    scrollSpeed: "scroll-speed-medium",
  },
  {
    image: "../img/album-12.png",
    vinylImage: "../img/visions-of-a-new-world/vinyl.png",
    cdImage: "../img/visions-of-a-new-world/cd.png",
    cassetteImage: "../img/visions-of-a-new-world/cassette.png",
    albumTitle: "visions of a new world",
    artist: "lonnie liston smith and the cosmic echoes",
    year: "1975",
    genre: "funk",
    vinylStock: [5, true],
    cdStock: [3, true],
    cassetteStock: [7, true],
    keywords:
      "Lonnie Liston Smith and the Cosmic Echoes Visions of a new World",
    id: "2",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Visions of a New World" er et album af Lonnie Liston Smith, udgivet i 1975. Det fusionerer jazz, funk og elektroniske elementer og skaber en spirituel og atmosfærisk lydoplevelse fyldt med eksperimentel musikalitet og positive budskaber.',
    path: "visions-of-a-new-world",
    scrollSpeed: "scroll-speed-extraslow",
  },
  {
    image: "../img/album-19.png",
    vinylImage: "../img/london-calling/vinyl.png",
    cdImage: "../img/london-calling/cd.png",
    cassetteImage: "../img/london-calling/cassette.png",
    albumTitle: "london calling",
    artist: "the clash",
    year: "1979",
    genre: "punk",
    vinylStock: [4, true],
    cdStock: [3, true],
    cassetteStock: [4, true],
    keywords: "The Clash London Calling",
    id: "3",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"London Calling" er et ikonisk album af The Clash fra 1979. Det kombinerer punk, reggae og rock og udforsker sociale og politiske emner med energi, attitude og musikalsk eksperimenteren.',
    path: "london-calling",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-34.png",
    vinylImage: "../img/war/vinyl.png",
    cdImage: "../img/war/cd.png",
    cassetteImage: "../img/war/cassette.png",
    albumTitle: "war",
    artist: "u2",
    year: "1983",
    genre: "punk",
    vinylStock: [4, true],
    cdStock: [1, true],
    cassetteStock: [6, true],
    keywords: "War U2",
    id: "4",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"War" er et revolutionerende album af U2 fra 1983. Det udforsker politiske og sociale temaer med energiske rockriffs og Bono´s karismatiske vokal, der kaster lys på krigens konsekvenser og håb om forandring.',
    path: "war",
    scrollSpeed: "scroll-speed-medium",
  },
  {
    image: "../img/secret-life.webp",
    vinylImage: "../img/secret-life/vinyl.png",
    cdImage: "../img/secret-life/cd.png",
    cassetteImage: "../img/secret-life/cassette.png",
    albumTitle: "secret life",
    artist: "fred again..",
    year: "2023",
    genre: "elektronisk",
    vinylStock: [2, true],
    cdStock: [3, true],
    cassetteStock: [0, true],
    keywords: "secret life fred again",
    id: "5",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Secret Life" er et følelsesladet og komplekst album af den britiske producer Fred Again... Med rørende tekster og samarbejder med Brian Eno og FKA twigs, er det et must-listen for fans af elektronisk og alternativ musik.',
    path: "secret-life",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-1.png",
    vinylImage: "../img/dizzy-mizz-lizzy/vinyl.png",
    cdImage: "../img/dizzy-mizz-lizzy/cd.png",
    cassetteImage: "../img/dizzy-mizz-lizzy/cassette.png",
    albumTitle: "dizzy mizz lizzy",
    artist: "dizzy mizz lizzy",
    year: "1994",
    genre: "rock",
    vinylStock: [4, true],
    cdStock: [2, true],
    cassetteStock: [0, false],
    keywords: "dizzy mizz lizzy",
    id: "6",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      "Dizzy Mizz Lizzy's selvbetitlede album er et dansk rockmesterværk. Udgivet i 1994 viser det Tim Christensens enestående sangskrivning, eksplosivt guitarspil og smittende melodier, der fanger lytterne med sin dynamiske lyd og efterlader et varigt indtryk.",
    path: "dizzy-mizz-lizzy",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-3.png",
    vinylImage: "../img/pure-heroine/vinyl.png",
    cdImage: "../img/pure-heroine/cd.png",
    cassetteImage: "../img/pure-heroine/cassette.png",
    albumTitle: "pure heroine",
    artist: "lorde",
    year: "2013",
    genre: "pop",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "lorde pure heroine",
    id: "7",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Pure Heroine" er Lordes debutalbum fra 2013. Med sin unikke stemme og skarpe tekster leverer hun et mørkt og ærligt blik på ungdommens erfaringer. Albummet fanger øjeblikke af ensomhed, selvrefleksion og oprør med en blanding af pop og elektroniske elementer.',
    path: "pure-heroine",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-4.png",
    vinylImage: "../img/inkarneret/vinyl.png",
    cdImage: "../img/inkarneret/cd.png",
    cassetteImage: "../img/inkarneret/cassette.png",
    albumTitle: "inkarneret",
    artist: "l.o.c.",
    year: "2003",
    genre: "hip-hop",
    vinylStock: [4, true],
    cdStock: [2, true],
    cassetteStock: [0, false],
    keywords: "l.o.c. inkarneret loc",
    id: "8",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Inkarneret" er et dansk rapalbum fra 2014 af den talentfulde rapper Kesi. Med autentiske tekster og en pulserende lyd skaber han et dybtgående og energisk udtryk, der indkapsler hans rejse og livserfaringer.',
    path: "inkarneret",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-5.png",
    vinylImage: "../img/when-we-all-fall-asleep-where-do-we-go/vinyl.png",
    cdImage: "../img/when-we-all-fall-asleep-where-do-we-go/cd.png",
    cassetteImage: "../img/when-we-all-fall-asleep-where-do-we-go/cassette.png",
    albumTitle: "when we all fall asleep, where do we go?",
    artist: "billie eilish",
    year: "2019",
    genre: "pop",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "billie eilish when we all fall asleep where do we go",
    id: "9",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"When We All Fall Asleep, Where Do We Go?" er Billie Eilishs debutalbum fra 2019. Det er en mørk og drømmende rejse fyldt med skæve produktioner, dystre tekster og Eilishs unikke vokal, der udforsker temaer som frygt, kærlighed og ungdommelig angst.',
    path: "when-we-all-fall-asleep-where-do-we-go",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-6.png",
    vinylImage: "../img/six-feet-beneath-the-moon/vinyl.png",
    cdImage: "../img/six-feet-beneath-the-moon/cd.png",
    cassetteImage: "../img/six-feet-beneath-the-moon/cassette.png",
    albumTitle: "6 feet beneath the moon",
    artist: "king krule",
    year: "2013",
    genre: "rock",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "6 feet beneath the moon six feet beneath the moon king krule",
    id: "10",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"6 Feet Beneath the Moon" er debutalbummet fra King Krule, udgivet i 2013. Med sin karakteristiske dybe stemme og en blanding af jazz, punk og indierock skaber han et dystert og stemningsfuldt lydlandskab, der udforsker isolation, tab og ungdommens kompleksiteter.',
    path: "six-feet-beneath-the-moon",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-7.png",
    vinylImage: "../img/norman-fucking-rockwell/vinyl.png",
    cdImage: "../img/norman-fucking-rockwell/cd.png",
    cassetteImage: "../img/norman-fucking-rockwell/cassette.png",
    albumTitle: "norman fucking rockwell",
    artist: "lana del rey",
    year: "2019",
    genre: "pop",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "lana del rey norman fucking rockwell",
    id: "11",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Norman Fucking Rockwell" er Lana Del Reys sjette studiealbum fra 2019. Med sin drømmende og introspektive lyd samt poetiske tekster skaber hun et magisk værk, der udforsker kærlighed, tab og Amerikas kulturelle landskab.',
    path: "norman-fucking-rockwell",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-8.png",
    vinylImage: "../img/bicicleta/vinyl.png",
    cdImage: "../img/bicicleta/cd.png",
    cassetteImage: "../img/bicicleta/cassette.png",
    albumTitle: "bicicleta",
    artist: "marcos valle",
    year: "1984",
    genre: "funk",
    vinylStock: [2, true],
    cdStock: [3, true],
    cassetteStock: [2, true],
    keywords: "bicicleta marcos valle",
    id: "12",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Bicicleta" er en EP af den brasilianske musiker Marcos Valle og præsenterer en livlig blanding af bossa nova, funk og jazz. Den viser Valles unikke stil og smittende rytmer i blot fem fængende numre.',
    path: "bicicleta",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-9.png",
    vinylImage: "../img/ginger/vinyl.png",
    cdImage: "../img/ginger/cd.png",
    cassetteImage: "../img/ginger/cassette.png",
    albumTitle: "ginger",
    artist: "brockhampton",
    year: "2019",
    genre: "hip-hop",
    vinylStock: [3, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "ginger brockhampton",
    id: "13",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Ginger" er et album af den amerikanske boyband Brockhampton og kendetegnes ved introspektive tekster og overdådig produktion. Det udforsker temaer som kærlighed, tab og personlig vækst og skaber en rå og følelsesladet musikalsk rejse.',
    path: "ginger",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-10.png",
    vinylImage: "../img/pablo-honey/vinyl.png",
    cdImage: "../img/pablo-honey/cd.png",
    cassetteImage: "../img/pablo-honey/cassette.png",
    albumTitle: "pablo honey",
    artist: "radiohead",
    year: "1993",
    genre: "rock",
    vinylStock: [2, true],
    cdStock: [3, true],
    cassetteStock: [0, false],
    keywords: "radiohead pablo honey",
    id: "14",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Pablo Honey" er Radioheads debutalbum fra 1993. Det præsenterer en blanding af alternativ rock og post-grunge, med sange som "Creep", der cementerede bandets plads i musikverdenen med deres karakteristiske lyd og følelsesmættede tekster.',
    path: "pablo-honey",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-11.png",
    vinylImage: "../img/alexander-o-neal/vinyl.png",
    cdImage: "../img/alexander-o-neal/cd.png",
    cassetteImage: "../img/alexander-o-neal/cassette.png",
    albumTitle: "alexander o'neal",
    artist: "alexander o'neal",
    year: "1985",
    genre: "soul",
    vinylStock: [4, true],
    cdStock: [2, true],
    cassetteStock: [2, true],
    keywords: "alexander o'neal",
    id: "15",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      'Alexander O´Neals selvbetitlede album er en tidløs R&B-klassiker. Udgivet i 1985 viser det hans bløde vokaler og sjælfulde levering og leverer hits som "If You Were Here Tonight" og "Criticize".',
    path: "alexander-o-neal",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-13.png",
    vinylImage: "../img/my-way/vinyl.png",
    cdImage: "../img/my-way/cd.png",
    cassetteImage: "../img/my-way/cassette.png",
    albumTitle: "my way",
    artist: "major harris",
    year: "1975",
    genre: "soul",
    vinylStock: [2, true],
    cdStock: [3, true],
    cassetteStock: [2, true],
    keywords: "major harris my way",
    id: "16",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"My Way" er Major Harris album fra 1975. Det er en sjælfuld udgivelse, der byder på glatte r&b-toner og Harris silkebløde vokal. Albummet indeholder hits som "Love Won\'t Let Me Wait", der cementerer Harris musikalske arv.',
    path: "my-way",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-14.png",
    vinylImage: "../img/horses-and-high-heels/vinyl.png",
    cdImage: "../img/horses-and-high-heels/cd.png",
    cassetteImage: "../img/horses-and-high-heels/cassette.png",
    albumTitle: "horses and high heels",
    artist: "marianne faithfull",
    year: "2011",
    genre: "rock",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "horses and high heels marianne faithfull",
    id: "17",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Horses and High Heels" er et fængslende album af Marianne Faithfull, udgivet i 2011. Med sin dragende stemme formidler hun rørende sange, der afspejler hendes livserfaringer med dybde og ægthed.',
    path: "horses-and-high-heels",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-15.png",
    vinylImage: "../img/evig-pint/vinyl.png",
    cdImage: "../img/evig-pint/cd.png",
    cassetteImage: "../img/evig-pint/cassette.png",
    albumTitle: "evig pint",
    artist: "kaizers orchestra",
    year: "2003",
    genre: "rock",
    vinylStock: [4, true],
    cdStock: [3, true],
    cassetteStock: [0, false],
    keywords: "kaizers orchestra evig pint",
    id: "18",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Evig pint" er Kaizers Orchestras andet studiealbum fra 2001. Det er en energisk og eksperimentel blanding af rock, punk og kabaret, der fanger lytterens opmærksomhed med sin teatralske stil og stærke musikalske fortællinger.',
    path: "evig-pint",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-16.png",
    vinylImage: "../img/before-the-rain/vinyl.png",
    cdImage: "../img/before-the-rain/cd.png",
    cassetteImage: "../img/before-the-rain/cassette.png",
    albumTitle: "before the rain",
    artist: "lee oskar",
    year: "1978",
    genre: "r&b",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "lee oskar before the rain",
    id: "19",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Before the Rain" er et album af Lee Oskar, udgivet i 1978. Med sin virtuose mundharmonikaspil og fusionen af funk, jazz og world music, skaber det en atmosfærisk lydoplevelse med dybde og variation.',
    path: "before-the-rain",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-17.png",
    vinylImage: "../img/on-love/vinyl.png",
    cdImage: "../img/on-love/cd.png",
    cassetteImage: "../img/on-love/cassette.png",
    albumTitle: "on love",
    artist: "david t. walker",
    year: "1976",
    genre: "jazz",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "david t walker on love",
    id: "20",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      "\"On Love\" er David T. Walker's album fra 1976. Det er en smuk og stemningsfuld udgivelse, der fletter jazz, soul og funk sammen med Walker's virtuose guitarspil, og skaber en lyd af ren kærlighed og musikalisk magi.",
    path: "on-love",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-18.png",
    vinylImage: "../img/atom-heart-mother/vinyl.png",
    cdImage: "../img/atom-heart-mother/cd.png",
    cassetteImage: "../img/atom-heart-mother/cassette.png",
    albumTitle: "atom heart mother",
    artist: "pink floyd",
    year: "1970",
    genre: "rock",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "atom heart mother pink floyd",
    id: "21",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Atom Heart Mother" er et album fra Pink Floyd, udgivet i 1970. Det er en eklektisk og eksperimentel blanding af progressiv rock og symfoniske elementer, der skaber en episk og hypnotisk lytteoplevelse.',
    path: "atom-heart-mother",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-20.png",
    vinylImage: "../img/bitches-brew/vinyl.png",
    cdImage: "../img/bitches-brew/cd.png",
    cassetteImage: "../img/bitches-brew/cassette.png",
    albumTitle: "bitches brew",
    artist: "miles davis",
    year: "1970",
    genre: "jazz",
    vinylStock: [3, true],
    cdStock: [3, true],
    cassetteStock: [0, false],
    keywords: "miles davis bitches brew",
    id: "22",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Bitches Brew" er et banebrydende album af Miles Davis, udgivet i 1970. Det fusionerer jazz med rock og elektroniske elementer, og skaber en eksperimenterende og improviseret lyd, der fortsætter med at inspirere musikere i dag.',
    path: "bitches-brew",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-21.png",
    vinylImage: "../img/legend/vinyl.png",
    cdImage: "../img/legend/cd.png",
    cassetteImage: "../img/legend/cassette.png",
    albumTitle: "legend",
    artist: "bob marley",
    year: "1984",
    genre: "r&b",
    vinylStock: [4, true],
    cdStock: [2, true],
    cassetteStock: [0, false],
    keywords: "legend bob marley",
    id: "23",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Legend" er et ikonisk album af Bob Marley, udgivet i 1984. Det er en samling af hans største hits, der fremhæver hans karismatiske stemme, engagerede tekster og uimodståelige reggae-riddims, hvilket cementerer hans musikalske arv.',
    path: "legend",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-22.png",
    vinylImage: "../img/nevermind/vinyl.png",
    cdImage: "../img/nevermind/cd.png",
    cassetteImage: "../img/nevermind/cassette.png",
    albumTitle: "nevermind",
    artist: "nirvana",
    year: "1991",
    genre: "rock",
    vinylStock: [2, true],
    cdStock: [3, true],
    cassetteStock: [0, false],
    keywords: "nirvana nevermind babydiller",
    id: "24",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Nevermind" er et ikonisk album af Nirvana, udgivet i 1991. Det definerede en hel generation med sin rå grunge-lyd og kraftfulde sange som "Smells Like Teen Spirit", der revolutionerede rockemusikken.',
    path: "nevermind",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-23.png",
    vinylImage: "../img/straight-outta-compton/vinyl.png",
    cdImage: "../img/straight-outta-compton/cd.png",
    cassetteImage: "../img/straight-outta-compton/cassette.png",
    albumTitle: "straight outta compton",
    artist: "n.w.a",
    year: "1988",
    genre: "hip-hop",
    vinylStock: [2, true],
    cdStock: [3, true],
    cassetteStock: [4, true],
    keywords: "n.w.a nwa n w a straight outta compton",
    id: "25",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Straight Outta Compton" er et banebrydende album af N.W.A, udgivet i 1988. Det udfordrede sociale normer og satte gang i en revolutionær bevægelse med sin ærlige skildring af ghetto-livet og politiske budskaber.',
    path: "straight-outta-compton",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-25.png",
    vinylImage: "../img/purple-rain/vinyl.png",
    cdImage: "../img/purple-rain/cd.png",
    cassetteImage: "../img/purple-rain/cassette.png",
    albumTitle: "purple rain",
    artist: "prince and the revolution",
    year: "1984",
    genre: "r&b",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [5, true],
    keywords: "prince and the revolution purple rain",
    id: "26",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Purple Rain" er Prince and The Revolutions ikoniske album fra 1984. Det fusionerer pop, rock og funk til en eksplosiv lydoplevelse, der fejrer Princes talentfulde sangskrivning, elektriske guitar og uforglemmelige hits som titelnummeret "Purple Rain".',
    path: "purple-rain",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-26.png",
    vinylImage: "../img/songs-in-the-key-of-life/vinyl.png",
    cdImage: "../img/songs-in-the-key-of-life/cd.png",
    cassetteImage: "../img/songs-in-the-key-of-life/cassette.png",
    albumTitle: "songs in the key of life",
    artist: "stevie wonder",
    year: "1976",
    genre: "r&b",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "songs in the key of life stevie wonder",
    id: "27",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Songs in the Key of Life" er et mesterværk af Stevie Wonder, udgivet i 1976. Det er en musikalsk tour de force, der fletter soul, funk og jazz sammen med dybe og rørende tekster, hvilket resulterer i en uforglemmelig lytteoplevelse.',
    path: "songs-in-the-key-of-life",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-27.png",
    vinylImage: "../img/kind-of-blue/vinyl.png",
    cdImage: "../img/kind-of-blue/cd.png",
    cassetteImage: "../img/kind-of-blue/cassette.png",
    albumTitle: "kind of blue",
    artist: "miles davis",
    year: "1959",
    genre: "jazz",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "kind of blue miles davis",
    id: "28",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Kind of Blue" er et legendarisk album af Miles Davis, udgivet i 1959. Det er et milepæl inden for jazzhistorien og definerer cool jazz med sin improvisation, subtile harmonier og enestående stemning.',
    path: "kind-of-blue",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-28.png",
    vinylImage: "../img/ready-to-die/vinyl.png",
    cdImage: "../img/ready-to-die/cd.png",
    cassetteImage: "../img/ready-to-die/cassette.png",
    albumTitle: "ready to die",
    artist: "the notorious b.i.g.",
    year: "1994",
    genre: "hip-hop",
    vinylStock: [3, true],
    cdStock: [3, true],
    cassetteStock: [0, false],
    keywords:
      "the notorious big ready to die the notorious b.i.g. the notorious b i g",
    id: "29",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"The Notorious B.I.G.´s Ready to Die" er et ikonisk hiphop-album fra 1994. Det viser Biggie Smalls´ imponerende rapskills, ærlige tekster og gennemslagskraftige beats, der solidificerede hans status som en af genrens største kunstnere.',
    path: "ready-to-die",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-29.png",
    vinylImage: "../img/led-zeppelin-iv/vinyl.png",
    cdImage: "../img/led-zeppelin-iv/cd.png",
    cassetteImage: "../img/led-zeppelin-iv/cassette.png",
    albumTitle: "led zeppelin iv",
    artist: "led zeppelin",
    year: "1971",
    genre: "rock",
    vinylStock: [3, true],
    cdStock: [0, false],
    cassetteStock: [4, true],
    keywords: "led zeppelin iv",
    id: "30",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Led Zeppelin IV" er et legendarisk rockalbum fra 1971. Det definerer Led Zeppelins musikalske arv med tidløse hits som "Stairway to Heaven" og udviser deres ekspertise inden for blues, rock og folkemusik.',
    path: "led-zeppelin-iv",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-30.png",
    vinylImage: "../img/nashville-skyline/vinyl.png",
    cdImage: "../img/nashville-skyline/cd.png",
    cassetteImage: "../img/nashville-skyline/cassette.png",
    albumTitle: "nashville skyline",
    artist: "bob dylan",
    year: "1969",
    genre: "rock",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "bob dylan nashville skyline",
    id: "31",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Nashville Skyline" er Bob Dylans niende studiealbum fra 1969. Det er en charmerende og melodiøs udgivelse, der markerer hans overgang til en mere country-inspireret lyd og indeholder klassikere som "Lay Lady Lay" og "Tonight I\'ll Be Staying Here with You".',
    path: "nashville-skyline",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-31.png",
    vinylImage: "../img/ziggy-stardust/vinyl.png",
    cdImage: "../img/ziggy-stardust/cd.png",
    cassetteImage: "../img/ziggy-stardust/cassette.png",
    albumTitle: "the rise and fall of ziggy stardust and the spiders from mars",
    artist: "david bowie",
    year: "1972",
    genre: "punk",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords:
      "the rise and fall of ziggy stardust and the spiders from mars david bowie",
    id: "32",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"The Rise and Fall of Ziggy Stardust and the Spiders from Mars" er et ikonisk konceptalbum af David Bowie, udgivet i 1972. Det introducerer Ziggy Stardust-karakteren og byder på en blanding af glam rock, science fiction-temaer og Bowie´s unikke stil.',
    path: "ziggy-stardust",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-32.png",
    vinylImage: "../img/electric-ladyland/vinyl.png",
    cdImage: "../img/electric-ladyland/cd.png",
    cassetteImage: "../img/electric-ladyland/cassette.png",
    albumTitle: "electric ladyland",
    artist: "the jim hendrix experience",
    year: "1968",
    genre: "rock",
    vinylStock: [2, true],
    cdStock: [3, true],
    cassetteStock: [4, true],
    keywords: "electric ladyland the jim hendrix experience",
    id: "33",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Electric Ladyland" er et banebrydende album af The Jimi Hendrix Experience, udgivet i 1968. Det udforsker grænserne for rockmusik med Hendrix´s virtuose guitarfærdigheder og eksperimenterende lydlandskaber, der skaber et tidløst og genredefinerende værk.',
    path: "electric-ladyland",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-33.png",
    vinylImage: "../img/at-san-quentin/vinyl.png",
    cdImage: "../img/at-san-quentin/cd.png",
    cassetteImage: "../img/at-san-quentin/cassette.png",
    albumTitle: "at san quentin",
    artist: "johnny cash",
    year: "1969",
    genre: "rock",
    vinylStock: [4, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "johnny cash at san quentin",
    id: "34",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"At San Quentin" er Johnny Cashs livealbum fra 1969, optaget i fængslet San Quentin. Med sin rå energi og ærlige udtryk fanger det Cashs karisma og rebelske ånd, og indeholder hits som "A Boy Named Sue" og "Folsom Prison Blues".',
    path: "at-san-quentin",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-35.png",
    vinylImage: "../img/gunfighter-ballads/vinyl.png",
    cdImage: "../img/gunfighter-ballads/cd.png",
    cassetteImage: "../img/gunfighter-ballads/cassette.png",
    albumTitle: "gunfighter ballads and trail songs",
    artist: "marty robbins",
    year: "1959",
    genre: "jazz",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "gunfighter ballads and trail songs marty robbins",
    id: "35",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Gunfighter Ballads and Trail Songs" er et ikonisk album af Marty Robbins, udgivet i 1959. Det hylder det vilde vesten med fortællende sange, der fanger dramaet og romantikken i cowboylivet, og cementerer Robbins´ status som en countrylegende.',
    path: "gunfighter-ballads",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-36.jpg",
    vinylImage: "../img/whipped-cream-and-other-delights/vinyl.png",
    cdImage: "../img/whipped-cream-and-other-delights/cd.png",
    cassetteImage: "../img/whipped-cream-and-other-delights/cassette.png",
    albumTitle: "whipped cream & other delights",
    artist: "herb alpert's tijuana brass",
    year: "1965",
    genre: "jazz",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "herb alperts tijuana brass whipped cream and other delights",
    id: "36",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Whipped Cream and Other Delights" er Herb Alperts Tijuana Brass album fra 1965. Med sin sprudlende og livlige mariachi-stil skaber det en festlig atmosfære fyldt med velkendte hits som "A Taste of Honey" og "Whipped Cream".',
    path: "whipped-cream-and-other-delights",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-37.png",
    vinylImage: "../img/dansktop/vinyl.png",
    cdImage: "../img/dansktop/cd.png",
    cassetteImage: "../img/dansktop/cassette.png",
    albumTitle: "dansktop",
    artist: "ukendt kunstner",
    year: "2023",
    genre: "hip-hop",
    vinylStock: [4, true],
    cdStock: [0, false],
    cassetteStock: [2, true],
    keywords: "ukendt kunstner dansktop",
    id: "37",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Dansktop" er musik-året 2023´s helt store overraskelse. Ukendt Kunstner er tilbage, det er blevet gamle, og falder i søvn til festerne. Men det det har ikke gjort deres lyrik- og lydunivers mindre spændende.',
    path: "dansktop",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-38.png",
    vinylImage: "../img/mere-end-en-klub/vinyl.png",
    cdImage: "../img/mere-end-en-klub/cd.png",
    cassetteImage: "../img/mere-end-en-klub/cassette.png",
    albumTitle: "mere end en klub",
    artist: "folkeklubben",
    year: "2023",
    genre: "pop",
    vinylStock: [4, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "mere end en klub folkeklubben",
    id: "38",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      'Folkeklubben er en relevant trio i 2023 med albummet "Vi er mere end en klub". Inspireret af fransk rap, svensk elektropop og John Coltrane, leverer de deres mest dynamiske og ambitiøse plade til dato. successfuldt orkester med guld- og platinplader.',
    path: "mere-end-en-klub",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-39.png",
    vinylImage: "../img/mythologies/vinyl.png",
    cdImage: "../img/mythologies/cd.png",
    cassetteImage: "../img/mythologies/cassette.png",
    albumTitle: "mythologies",
    artist: "thomas bangalter",
    year: "2023",
    genre: "klassisk",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "thomas bangalter mythologies",
    id: "39",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Mythologies" er Thomas Bangalters første orkesterkomposition, skabt efter anmodning fra koreografen Angelin Preljocaj til balletten med samme navn. Det er et storslået og lyrisk værk, fremført af Orchestre National Bordeaux Aquitaine, dirigeret af Romain Dumas. Her genopfinder Bangalter, medstifter af Daft Punk, sit forhold til kompositionen.',
    path: "mythologies",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-40.png",
    vinylImage: "../img/random-access-memory/vinyl.png",
    cdImage: "../imgrandom-access-memory/cd.png",
    cassetteImage: "../img/random-access-memory/cassette.png",
    albumTitle: "random access memory",
    artist: "daft punk",
    year: "2023",
    genre: "elektronisk",
    vinylStock: [2, true],
    cdStock: [0, false],
    cassetteStock: [3, true],
    keywords: "random access memory daft punk",
    id: "40",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Random Access Memories" er Daft Punks banebrydende album fra 2013. Det fusionerer elektronisk musik med liveinstrumenter og gæsteoptrædener, og skaber en nostalgisk og futuristisk lydoplevelse, der fejrer musikkens tidløse kraft.',
    path: "random-access-memory",
    scrollSpeed: "scroll-speed-slow",
  },
  {
    image: "../img/album-41.png",
    vinylImage: "../img/local-hero/vinyl.png",
    cdImage: "../img/local-hero/cd.png",
    cassetteImage: "../img/local-hero/cassette.png",
    albumTitle: "local hero",
    artist: "mark knopfler",
    year: "1983",
    genre: "rock",
    vinylStock: [4, true],
    cdStock: [0, false],
    cassetteStock: [0, false],
    keywords: "local hero mark knopfler",
    id: "41",
    vinylPrice: "169",
    cdPrice: "99",
    cassettePrice: "139",
    description:
      '"Local Hero" er et soundtrackalbum af Mark Knopfler, udgivet i 1983. Det ledsager filmen af samme navn og byder på Knopflers karakteristiske guitararbejde og atmosfæriske kompositioner, der fanger skønheden i det skotske landskab.',
    path: "local-hero",
    scrollSpeed: "scroll-speed-slow",
  },

  // {
  //     image: "../img/",
  //     vinylImage: "../img//vinyl.png",
  //     cdImage: "../img//cd.png",
  //     cassetteImage: "../img//cassette.png",
  //     albumTitle: "",
  //     artist: "",
  //     year: "",
  //     genre: "",
  //     vinylStock: [2, true],
  //     cdStock: [3, true],
  //     cassetteStock: [0, true],
  //     keywords: "",
  //     id: "",
  //     vinylPrice: "",
  //     cdPrice: "",
  //     cassettePrice: "",
  //     description: '',
  //     path: '',
  //     scrollSpeed: "scroll-speed-slow"
  // },
];

export const history = [
  {
    image: "mick-indeholder-intet.png",
    title: "Startede som punk-distributør",
    description:
      "Mick D'Astugues åbnede for første gang BadstueRocks døre i 1973. Dengang syntes han, at der, i Aarhus, var et hul i markedet, når det kom til den britiske punkscene. Dog var denne genre ikke den eneste, han distri-buerede. Det var eftersigende reggaetoner fra Pablo Augustus' melotron, der oftest mødte dig, når du trådte ind i butikken.",
    alttag: "Grundlæggeren af BadstueRock, Mick D'Astugues I butikken",
  },
  {
    image: "runde-bjorn.png",
    title: "Björn tog over",
    description:
      "Som Mick selv sagde det, kunne han i 2012 ikke indeholde mere musik. Han var mættet og følte, at han sad fast i en ældre tid, og tiden var derfor inde til at give nøglerne videre. Björn havde siden 2003 arbejdet i butikken og var derfor veloplært og den bedste kandidat til at overtage nøglerne. Dette var også tilfældet, og det skulle vise sig at være en god beslutning.",
    alttag: "Nuværende indehaver af BadstueRock, Björn Lydén i butikken",
  },
  {
    image: "facade.png",
    title: "Ny visuel identitet",
    description:
      "Som det seneste kapitel i BadstueRocks historie, har butikkens visuelle identitet fået et 'overhaul'. Dette gælder logo og især deres digitale tilstedeværelse, hvor vi langt om længe har fået en hjemmeside, der afspejler butikken og fungerer som forlængelse af denne.",
    alttag: "BadstueRocks Facade",
  },
];

export const workers = [
  {
    image: "flade-bjorn.png",
    firstName: "Björn",
    lastName: "Lydén",
    title: "Indehaver",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius iure ex repudiandae veritatis, tempore veniam atque! Unde libero enim consequatur eius, accusamus.",
  },
  {
    image: "helgen.png",
    firstName: "Thomas",
    lastName: "Helgén",
    title: "Butiksassistent",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius iure ex repudiandae veritatis, tempore veniam atque! Unde libero enim consequatur eius, accusamus.",
  },
  {
    image: "malle.png",
    firstName: "Amalie",
    lastName: "Ariél",
    title: "SoMe-Ansvarlig",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius iure ex repudiandae veritatis, tempore veniam atque! Unde libero enim consequatur eius, accusamus.",
  },
];

export const posts = [
  {
    id: "CrkyToTM2b5",
    name: "BadstueRock",
    handle: "badstuerock",
  },
  {
    id: "Csn1hCcMC4P",
    name: "BadstueRock",
    handle: "badstuerock",
  },
  {
    id: "CnCmJ-sM40r",
    name: "BadstueRock",
    handle: "badstuerock",
  },
  {
    id: "CstPheisaeL",
    name: "BadstueRock",
    handle: "badstuerock",
  },
  {
    id: "Cn4e5aHs41K",
    name: "BadstueRock",
    handle: "badstuerock",
  },
  {
    id: "CfntGF8sM2C",
    name: "BadstueRock",
    handle: "badstuerock",
  },
];

// {
//   id: "",
//   name: "",
//   handle: "",
// }
